// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQNVN55i-Aax6dpwKfR930KmQq5N7ttY',
    appId: '1:930782535691:web:ab116a23ed00bc13baa70e',
    messagingSenderId: '930782535691',
    projectId: 'unimatch-bab2e',
    authDomain: 'unimatch-bab2e.firebaseapp.com',
    storageBucket: 'unimatch-bab2e.firebasestorage.app',
    measurementId: 'G-17VH36XX02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGOARj8ZqCnQOznPniTRwPm46WtEekIh4',
    appId: '1:930782535691:android:d165e3166691b4c6baa70e',
    messagingSenderId: '930782535691',
    projectId: 'unimatch-bab2e',
    storageBucket: 'unimatch-bab2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNl6hDpvwMF9xU1BF4YCs2w77QTgslA8',
    appId: '1:930782535691:ios:51a8145439f69c68baa70e',
    messagingSenderId: '930782535691',
    projectId: 'unimatch-bab2e',
    storageBucket: 'unimatch-bab2e.firebasestorage.app',
    iosBundleId: 'com.example.unimatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNl6hDpvwMF9xU1BF4YCs2w77QTgslA8',
    appId: '1:930782535691:ios:51a8145439f69c68baa70e',
    messagingSenderId: '930782535691',
    projectId: 'unimatch-bab2e',
    storageBucket: 'unimatch-bab2e.firebasestorage.app',
    iosBundleId: 'com.example.unimatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhQNVN55i-Aax6dpwKfR930KmQq5N7ttY',
    appId: '1:930782535691:web:82dc50d6ce091e01baa70e',
    messagingSenderId: '930782535691',
    projectId: 'unimatch-bab2e',
    authDomain: 'unimatch-bab2e.firebaseapp.com',
    storageBucket: 'unimatch-bab2e.firebasestorage.app',
    measurementId: 'G-3ME45NX8ME',
  );
}
