// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'services/firestore_service.dart';
import 'services/storage_service.dart';
import 'services/fcm_service.dart';
import 'providers/auth_provider.dart';
import 'providers/match_provider.dart';
import 'providers/swipe_provider.dart';
import 'screens/shell/app_shell.dart';
import 'screens/auth/login_screen.dart';
import 'repositories/auth_repository.dart';
import 'repositories/swipe_repository.dart';
import 'repositories/match_repository.dart';
import 'repositories/user_repository.dart';
import 'repositories/chat_repository.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await FCMService().init();
  runApp(const TutorMatchApp());
}

class TutorMatchApp extends StatelessWidget {
  const TutorMatchApp({super.key});

  @override
  Widget build(BuildContext context) {
    // ── Singletons ──────────────────────────────────────────────────
    final firestoreService = FirestoreService();
    final storageService = StorageService();

    final authRepo = AuthRepository(firestoreService);
    final userRepo = UserRepository(firestoreService);
    final swipeRepo = SwipeRepository(firestoreService);
    final matchRepo = MatchRepository(firestoreService);
    final chatRepo = ChatRepository(firestoreService);

    return MultiProvider(
      providers: [
        Provider<FirestoreService>.value(value: firestoreService),
        Provider<StorageService>.value(value: storageService),
        Provider<ChatRepository>.value(value: chatRepo),
        ChangeNotifierProvider(create: (_) => AuthProvider(authRepo)),
      ],
      child: Consumer<AuthProvider>(
        builder: (ctx, auth, _) {
          final user = auth.user;

          // 1. Define the core app widget
          Widget app = MaterialApp(
            title: 'Tutor Match',
            debugShowCheckedModeBanner: false,
            theme: _buildTheme(Brightness.light),
            darkTheme: _buildTheme(Brightness.dark),
            themeMode: ThemeMode.system,
            home: auth.status == AuthStatus.authenticated
                ? const AppShell()
                : const LoginScreen(),
          );

          // 2. Only wrap with MultiProvider if we have a user (and thus, providers)
          if (user != null) {
            return MultiProvider(
              providers: [
                ChangeNotifierProvider(
                  create: (_) => SwipeProvider(swipeRepo, user.uid, user.role),
                ),
                ChangeNotifierProvider(
                  create: (_) => MatchProvider(matchRepo, userRepo, user.uid),
                ),
              ],
              child: app,
            );
          }

          // 3. Return plain app for unauthenticated users
          return app;
        },
      ),
    );
  }

  ThemeData _buildTheme(Brightness brightness) {
    final isDark = brightness == Brightness.dark;
    final seed = const Color(0xFF6C63FF); // Purple seed

    return ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorSchemeSeed: seed,
      fontFamily: 'Inter',
      appBarTheme: AppBarTheme(
        centerTitle: false,
        elevation: 0,
        scrolledUnderElevation: 1,
        backgroundColor:
            isDark ? const Color(0xFF1A1A2E) : Colors.white,
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        type: BottomNavigationBarType.fixed,
        selectedItemColor: Color(0xFF6C63FF),
        showUnselectedLabels: true,
      ),
    );
  }
}